from .comment import CommentForm, PartialCommentForm
from .lector import LectorForm, PartialLectorForm
from .classifield import ClassifieldForm, PartialClassifieldForm
from .news import NewsForm, PartialNewsForm
from .redator import RedatorForm, PartialRedatorForm
from .journalist import JournalistForm, PartialJournalistForm
from .section import SectionForm, PartialSectionForm
from .subsection import SubSectionForm, PartialSubSectionForm 
from .offer import OfferForm, PartialOfferForm
from .userAuthenticated import UserAuthenticatedForm, PartialUserAuthenticatedForm 